import { Product } from './types'

export const PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Botanical Glow Serum',
    slug: 'botanical-glow-serum',
    description: 'A lightweight daily serum that hydrates deeply and revives dull, tired skin.',
    long_description:
      'Our Botanical Glow Serum is built for everyday performance. The texture sinks in quickly, layers cleanly under moisturizer and sunscreen, and helps the skin look brighter and more balanced over time. It is ideal when your routine needs hydration plus visible glow support without a heavy finish. Powered by Niacinamide and Hyaluronic Acid, this serum works at the cellular level to restore moisture and visibly reduce the appearance of pores.',
    price: 62.0,
    category: 'serum',
    image_url: '/serum.png',
    skin_type: 'Normal, combination, and oily skin',
    size: '30ml | 1.0 fl oz',
    key_ingredient: 'Niacinamide',
    ingredients: ['Niacinamide', 'Hyaluronic Acid', 'Squalane', 'Green Tea Extract'],
    concerns: ['Dullness', 'Uneven texture', 'Early dehydration'],
    how_to_use: [
      'Apply 2–3 drops on clean, slightly damp skin.',
      'Press gently over face and neck until absorbed.',
      'Follow with Day Cream; finish with SPF in morning routine.',
    ],
    stock_quantity: 50,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '2',
    name: 'Luminance Day Cream',
    slug: 'luminance-day-cream',
    description: 'A barrier-supporting moisturizer that keeps skin soft, smooth, and comfortable all day.',
    long_description:
      'Day Cream is designed for long daytime comfort. It locks in hydration, supports the skin barrier, and creates a smooth base under sunscreen and makeup. The finish is breathable and non-greasy, making it easy to wear in warm or humid weather. Formulated with Ceramides and Peptide Complex to strengthen the skin barrier and fight signs of aging.',
    price: 48.0,
    category: 'day-cream',
    image_url: '/day-cream.png',
    skin_type: 'Normal, dry, and combination skin',
    size: '50ml | 1.7 fl oz',
    key_ingredient: 'Ceramides',
    ingredients: ['Ceramides', 'Panthenol', 'Peptide Complex', 'Vitamin E'],
    concerns: ['Dryness', 'Barrier support', 'Rough texture'],
    how_to_use: [
      'Use after Serum in the morning and afternoon as needed.',
      'Massage a pea-sized amount across face and neck.',
      'Layer sunscreen on top during daytime exposure.',
    ],
    stock_quantity: 75,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '3',
    name: 'Pure Clarity Cleanser',
    slug: 'pure-clarity-cleanser',
    description: 'A gentle gel cleanser that removes buildup without stripping essential moisture.',
    long_description:
      'Cleanser gives you a fresh reset without that tight, dry after-feel. The low-foam gel lifts sunscreen, pollution, and excess oil while maintaining comfort. It is a dependable first step for both morning and evening routines. Enriched with Aloe Vera and Chamomile Extract to soothe even the most sensitive skin while delivering a thorough, refreshing cleanse.',
    price: 29.0,
    category: 'cleanser',
    image_url: '/cleanser.png',
    skin_type: 'All skin types, including sensitive skin',
    size: '150ml | 5.0 fl oz',
    key_ingredient: 'Aloe Vera',
    ingredients: ['Aloe Vera', 'Glycerin', 'Rice Amino Acids', 'Chamomile Extract'],
    concerns: ['Daily buildup', 'Sensitive cleansing', 'Post-wash tightness'],
    how_to_use: [
      'Massage onto damp skin for 30–40 seconds.',
      'Rinse with lukewarm water and pat dry gently.',
      'Follow with Serum and Day Cream for complete routine.',
    ],
    stock_quantity: 100,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '4',
    name: 'The Complete Ritual Set',
    slug: 'complete-ritual-set',
    description: 'The full SRI BLOOM routine — Cleanser, Serum, and Day Cream — at a curated price.',
    long_description:
      'Start with Cleanser to reset the skin, apply Serum to target hydration and brightness, then lock in comfort with Day Cream. This complete set helps your products perform better and keeps your routine consistent. Together, they form a synergistic system designed to cleanse, treat, and protect your skin every day.',
    price: 125.0,
    category: 'bundle',
    image_url: '/hero-products.png',
    skin_type: 'All skin types',
    size: 'Full size trio set',
    key_ingredient: 'Botanical Complex',
    ingredients: ['Niacinamide', 'Ceramides', 'Aloe Vera', 'Hyaluronic Acid', 'Green Tea Extract'],
    concerns: ['Complete routine', 'Daily hydration', 'Skin harmony'],
    how_to_use: [
      'Cleanse morning and evening with Pure Clarity Cleanser.',
      'Apply 2–3 drops of Botanical Glow Serum on damp skin.',
      'Finish with Luminance Day Cream to lock in moisture.',
    ],
    stock_quantity: 30,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
]
